### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/bike-coop-theme#18]
We should implement a blog, it should have the following features:

- Show blog posts on the home page as seen in the [home page mockup.](https://github.com/CodeForFoco/bike-coop/blob/master/assets/FCBC%20Website_2.pdf)
- Have a page for viewing blog posts.
- Have a list page for listing blog posts.

**Comment by abettermap** [comment]
@JordanMajd The [notes](https://github.com/CodeForFoco/bike-coop/blob/master/assets/FCBC%20Website%20Notes.pdf) say to drop the blog. 

Which one is correct?

**Comment by JordanMajd** [comment]
@abettermap 

You are correct, originally they did want it dropped; however, at the meeting they decided they wanted one.

**Comment by abettermap** [comment]
@JordanMajd 

Yikes, that home page is gonna be BIZZAY!

I can try to tackle this one but I need to make some progress on #15 first. I'll get some advice at Thursday's meeting if no one has claimed this issue by then.

**Comment by redisforlosers** [comment]
This should be easy to implement with WP builtin blog functionality.  Do we know how they want it displayed?  I would suggest a link to the blog on the homepage, as well as a truncated version of the most recent blog post. If that sounds like a good plan I can start tackling it.

**Comment by abettermap** [comment]
@redisforlosers 
Sorry, meant to reply sooner. The only info I have is from the comp, which kinda looks like excerpts like you suggested, so that sounds like a plan. Let's discuss at the meeting tonight if you are there.

**Comment by radd2004** [comment]
@radd2004 Taking over blog
