### ISSUE TITLE
Adjust titles of photo blocks 

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/bike-coop-theme#41]
From Jeff's Email (issue #36)

The area on the layout with the photo blocks titles EARN A BIKE, FIX YOUR BIKE, ABANDONED BIKES, etc, is for our most important or primary content. The area on the layout under that is for secondary content. Could be specific bikes for sale, could be upcoming events, could be community events we want to plug. The photos need to be smaller with more room for copy because these may or may not link to additional web pages. It could be single horizontal blocks with photos on the left and copy on the right, as shown, or two column blocks. The main point is, the photos will be smaller and there will be more copy for items listed in this area.

**Comment by abettermap** [comment]
I think we should forego the plugin stuff in favor of Elementor for highly dynamic/customizable things like this.
