### ISSUE TITLE
Change top-bar navigation links

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/bike-coop-theme#43]
From Jeff's email (issue #36)

1. Change the events link at the top of the page to programs. All our events will either be self-contained in one of the two content areas on the home page or on Facebook, we do not need a separate page for them on the website. We do want a single page for programs that gives details on programs like Earn A Bike and Abandoned Bikes. 
2. Delete the blog link at the top of the page. If we do anything with blog posts, we can use the secondary content area at the bottom of the page for it.

**Comment by abettermap** [comment]
I can show them how to edit the navigation menu.

**Comment by abettermap** [comment]
Combined this with and closed #42 as they are almost the same issue
