### ISSUE TITLE
External links open in new tab

### ISSUE THREAD

**Issue by JordanMajd** [CodeForFoco/bike-coop-theme#45]
From Jeff's email (issue #36)

Links to Facebook (or any external site) should open another window or tab to make it easy to get back to our site.

**Comment by abettermap** [comment]
I can fix this in the theme if there any spots with this problem, and wp users can handle the rest.

**Comment by abettermap** [comment]
@JordanMajd I think it was just the links in the "Upcoming Events" section, and the PayPal links on Donate page, but let me know if you spot any others (not counting what's in the content) and we can reopen.
